# Generated by Django 2.2 on 2019-04-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': '日记', 'verbose_name_plural': '日记列表'},
        ),
    ]
